name: Check

on:
  push:

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Restore
        uses: ./.github/actions/restore

      - name: Audit
        continue-on-error: true
        run: |
          dotnet list package --vulnerable --include-transitive | tee audit.txt
          grep -q "following vulnerable packages" audit.txt && exit 1 || exit 0

      - name: Format
        run: |
          dotnet format --verify-no-changes

      - name: Setup mono
        run: |
          sudo apt-get update
          sudo apt-get -y --no-install-recommends install mono-complete

      - name: Test
        run: |
          dotnet test -f net10.0 --report-spekt-junit --coverlet --coverlet-output-format cobertura
          dotnet test -f net48 --report-spekt-junit --coverlet --coverlet-output-format cobertura

      - name: Codecov test results
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5
        with:
          report_type: test_results
          files: ./tests/bin/Debug/*/TestResults/TestResults.xml
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Codecov coverage
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5
        with:
          files: ./tests/bin/Debug/*/TestResults/coverage.cobertura.xml
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Pack
        run: dotnet pack

      - name: Generate SBOM
        run: |
          dotnet tool restore
          dotnet dotnet-CycloneDX IfcGuid.slnx -F json --filename sbom.cdx.json
          jq . sbom.cdx.json
