name: Check

on:
  push:

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: Restore
        uses: ./.github/actions/restore

      - name: Audit
        continue-on-error: true
        run: |
          dotnet list package --vulnerable --include-transitive | tee audit.txt
          grep -q "following vulnerable packages" audit.txt && exit 1 || exit 0

      - name: Format
        run: |
          dotnet format --verify-no-changes

      - name: Setup mono
        run: |
          sudo apt-get update
          sudo apt-get -y --no-install-recommends install mono-complete

      - name: Test
        run: |
          dotnet test -f net10.0 --logger:"junit;LogFilePath=../junit.core.xml" --collect:"XPlat Code Coverage"
          dotnet test -f net48 --logger:"junit;LogFilePath=../junit.framework.xml" --collect:"XPlat Code Coverage"

      - name: Codecov test results
        uses: codecov/test-results-action@47f89e9acb64b76debcd5ea40642d25a4adced9f # v1
        with:
          files: ./junit.core.xml,./junit.framework.xml
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Codecov coverage
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5
        with:
          files: ./tests/TestResults/*/coverage.cobertura.xml
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Pack
        run: dotnet pack
